<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2.2 setup script
 * Date: Sat, 03 Mar 2018 17:02:17 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: main [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'main';
$cfg['Servers'][$i]['host'] = 'DB_HOST';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '5a9ad51259ffe3.46320307';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

