version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  mutillidae:
    build: mutillidae
    restart: always
    environment:
      DB_PASSWORD: my-secret-pw
    ports:
      - 80:80
      - 443:443

